# Uncomment the next line to define a global platform for your project
platform :ios, "9.0"

target "MyMorningCoffee" do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyMorningCoffee

  $Firebase = "5.3.0"
  pod "Firebase/Core", $Firebase
  pod "Firebase/Database", $Firebase

  target "MyMorningCoffeeTests" do
    inherit! :search_paths
    # Pods for testing
  end
end
